server:
  port: 8090

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://49.233.2.43:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    password: 123456
  redis:
    # Redis 单机单实例
    database: 0
    password: 19920820
    #    host: 49.233.2.43
    #    port: 6379
    sentinel:
      master: mymaster
      nodes: 49.233.2.43:26379,49.233.2.43:26380,123.57.78.73:26379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl