server:
  port: 8033

spring:
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
    url: jdbc:mysql://49.233.2.43:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    password: 123456
    username: root
  data:
    elasticsearch:
      cluster-nodes: 123.57.78.73:9300
      cluster-name: es-dev
